services:
  backend-green:
    build: ./backend
    container_name: backend-green
    networks:
      - app-network

  frontend-green:
    build: ./frontend
    container_name: frontend-green
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
