version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  # backend
  backend:
    build: ./backend
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # frontend
  frontend:
    build: ./frontend
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - app-network

  # redis
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - app-network

  # mysql
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # nginx
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql-data:
  redis-data:
