spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      exprire-time: ${REDIS_EXPIRE_TIME}


# aws s3
aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
  stack:
    auto: false
  credentials:
    access-key: ${AWS_S3_ACCESS}
    secret-key: ${AWS_S3_SECRET}
    region: ${AWS_S3_REGION}